const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('public/assets/js/admin-dispatch.js','utf8');
function el(tag='div'){return {tag,children:[],events:{},value:'',disabled:false,hidden:false,textContent:'',open:false,append(...nodes){this.children.push(...nodes);},replaceChildren(...nodes){this.children=nodes;},setAttribute(){},addEventListener(type,fn){this.events[type]=fn;},showModal(){this.open=true;},close(){this.open=false;},querySelectorAll(selector){const result=[];function visit(node){if(node.tag===selector)result.push(node);for(const child of node.children||[])visit(child);}visit(this);return result;}};}
function setup(){const ids=Object.fromEntries(['dispatch-filters','dispatch-assign','dispatch-error','dispatch-list','dispatch-prev','dispatch-next','dispatch-summary','dispatch-page','dispatch-close','dispatch-reload','dispatch-candidate-search','dispatch-candidate-search-button','dispatch-candidate-prev','dispatch-candidate-next','dispatch-candidates','dispatch-assign-error','dispatch-title','dispatch-current','dispatch-candidate-page','dispatch-refresh','dispatch-candidate-filters'].map(id=>[id,el()]));ids['dispatch-filters'].elements=['search','status','assignment'].map(name=>({name,value:''}));const requests=[],timers=new Map(),docEvents={},windowEvents={},document={hidden:false,getElementById:id=>ids[id],createElement:el,addEventListener:(name,fn)=>docEvents[name]=fn};let timer=0;
  vm.runInNewContext(source,{document,window:{Sabjiwalah:{url:path=>'http://localhost'+path},SabjiwalahAdmin:{api:(path,options)=>new Promise((resolve,reject)=>requests.push({path,options,resolve,reject})),confirm:async()=>true,notify(){}},addEventListener:(name,fn)=>windowEvents[name]=fn},URLSearchParams,AbortController,Intl,Date,Math,Object,encodeURIComponent,setTimeout:(fn,delay)=>{timers.set(++timer,{fn,delay});return timer;},clearTimeout:id=>timers.delete(id),FormData:class{constructor(form){this.entries=form.elements.map(field=>[field.name,field.value]);}[Symbol.iterator](){return this.entries[Symbol.iterator]();}}});return {ids,requests,timers,document,docEvents,windowEvents};}
const flush=()=>new Promise(resolve=>setImmediate(resolve));
const order={uid:'ord_one',order_number:'SW <img src=x>',order_status:'ready_for_delivery',assignment_uid:null,rider_name:null,rider_status:null,waiting_minutes:16,delayed:true};
const queue=(items=[order])=>({items,pager:{total:items.length,page_count:items.length?1:0}});
const detail=(assignment=null,status='ready_for_delivery')=>({order:{order_number:order.order_number,order_status:status},assignments:assignment?[{uid:assignment,delivery_name:'Previous rider'}]:[]});
const candidates={items:[{uid:'usr_one',name:'<img sample rider>'}],pager:{total:1,page_count:1}};
function find(root,text){if(root.textContent===text)return root;for(const child of root.children||[]){const match=find(child,text);if(match)return match;}}
async function initial(s){s.requests[0].resolve({data:queue()});await flush();}
async function open(s){find(s.ids['dispatch-list'],'Assign').events.click();s.requests[1].resolve({data:detail()});await flush();s.requests[2].resolve({data:candidates});await flush();}
test('polling does not overlap, preserves filters and ignores obsolete responses',async()=>{const s=setup();s.ids['dispatch-filters'].elements[0].value='SW 1';s.ids['dispatch-filters'].events.submit({preventDefault(){}});assert.equal(s.requests.length,1);assert.equal(s.requests[0].options.signal.aborted,true);s.requests[0].resolve({data:queue()});await flush();assert.equal(s.ids['dispatch-list'].children.length,0);assert.match(s.requests[1].path,/search=SW\+1/);s.requests[1].resolve({data:queue()});await flush();assert.ok(find(s.ids['dispatch-list'],order.order_number));assert.match(find(s.ids['dispatch-list'],order.order_number).href,/SW%20%3Cimg/);assert.ok(find(s.ids['dispatch-list'],'Needs attention'));assert.equal([...s.timers.values()][0].delay,8000);});
test('assignment requests use observed ownership and close only after successful save',async()=>{const s=setup();await initial(s);await open(s);find(s.ids['dispatch-candidates'],'Assign').events.click();await flush();assert.equal(s.requests[3].options.method,'POST');assert.equal(s.requests[3].options.body.expected_assignment_uid,'none');assert.equal(s.requests[3].options.body.rider_uid,'usr_one');assert.equal(s.ids['dispatch-close'].disabled,true);s.requests[3].resolve({data:{assignment_uid:'das_new'}});await flush();assert.equal(s.ids['dispatch-assign'].open,false);assert.match(s.requests[4].path,/admin\/dispatch\?/);});
test('stale assignments and network ambiguity block further saves until order reload',async()=>{const s=setup();await initial(s);await open(s);find(s.ids['dispatch-candidates'],'Assign').events.click();await flush();s.requests[3].reject(Object.assign(new Error('Changed'),{status:409}));await flush();assert.equal(find(s.ids['dispatch-candidates'],'Assign').disabled,true);find(s.ids['dispatch-candidates'],'Assign').events.click();await flush();assert.equal(s.requests.length,4);s.ids['dispatch-reload'].events.click();s.requests[4].resolve({data:detail('das_latest')});await flush();s.requests[5].resolve({data:candidates});await flush();find(s.ids['dispatch-candidates'],'Assign').events.click();await flush();assert.equal(s.requests[6].options.body.expected_assignment_uid,'das_latest');});
test('polling leaves rider selections in place but disables changed assignment actions',async()=>{const s=setup();await initial(s);await open(s);const selection=s.ids['dispatch-candidates'].children[0];s.ids['dispatch-refresh'].events.click();s.requests[3].resolve({data:queue([{...order,assignment_uid:'das_other'}])});await flush();assert.equal(s.ids['dispatch-candidates'].children[0],selection);assert.equal(find(s.ids['dispatch-candidates'],'Assign').disabled,true);assert.match(s.ids['dispatch-assign-error'].textContent,/changed/);});
test('closing cancels late details and hidden pages pause polling',async()=>{const s=setup();await initial(s);find(s.ids['dispatch-list'],'Assign').events.click();s.ids['dispatch-close'].events.click();assert.equal(s.requests[1].options.signal.aborted,true);s.requests[1].resolve({data:detail()});await flush();assert.equal(s.requests.length,2);assert.equal(s.ids['dispatch-candidates'].children.length,0);s.document.hidden=true;s.docEvents.visibilitychange();assert.equal(s.timers.size,0);s.document.hidden=false;s.docEvents.visibilitychange();assert.equal(s.requests.length,3);s.windowEvents.pagehide();assert.equal(s.requests[2].options.signal.aborted,true);});
test('pickup prevents selection and no candidates has an actionable empty state',async()=>{const s=setup();await initial(s);find(s.ids['dispatch-list'],'Assign').events.click();s.requests[1].resolve({data:detail(null,'out_for_delivery')});await flush();assert.equal(s.requests.length,2);assert.match(s.ids['dispatch-assign-error'].textContent,/no longer ready/);s.ids['dispatch-close'].events.click();find(s.ids['dispatch-list'],'Assign').events.click();s.requests[2].resolve({data:detail()});await flush();s.requests[3].resolve({data:{items:[],pager:{total:0,page_count:0}}});await flush();assert.match(s.ids['dispatch-candidates'].children[0].textContent,/No available personnel/);});
