const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function element(tag='div') { return {tag,children:[],events:{},value:'',checked:false,disabled:false,hidden:false,textContent:'',append(...nodes){this.children.push(...nodes);},prepend(...nodes){this.children.unshift(...nodes);},replaceChildren(...nodes){this.children=nodes;},addEventListener(name,fn){this.events[name]=fn;},querySelectorAll(tag){const found=[];function visit(node){for(const child of node.children){if(child.tag===tag)found.push(child);visit(child);}}visit(this);return found;}}; }
const flush=()=>new Promise(resolve=>setImmediate(resolve));
const order={uid:'ord_one',order_number:'<img sample>',order_status:'out_for_delivery',payment_method:'cod',total_amount:120,customer_name:'Fixture',customer_phone:'9000000000',address_line:'Test',city:'City',postal_code:'700001'};
function rider(){const ids=Object.fromEntries(['delivery-list','delivery-message','delivery-refresh','delivery-logout','delivery-count'].map(id=>[id,element()])),calls=[],events={};vm.runInNewContext(fs.readFileSync('public/assets/js/delivery-completion.js','utf8'),{document:{getElementById:id=>ids[id],createElement:element},window:{Sabjiwalah:{url:path=>'/shop/'+path},confirm:()=>true,addEventListener:(name,fn)=>events[name]=fn,location:{reload(){events.reloaded=true;},assign(){}}},fetch:(path,options)=>new Promise((resolve,reject)=>calls.push({path,options,resolve,reject})),Error,Object,encodeURIComponent});return {ids,calls,events};}
function response(call,data,status=200){call.resolve({ok:status===200,status,json:async()=>({success:status===200,data,message:status===422?'Incorrect PIN':'Request failed'})});}
async function initialize(s){response(s.calls[0],{items:[order]});await flush();}
async function submit(s){const form=s.ids['delivery-list'].querySelectorAll('form')[0],inputs=form.querySelectorAll('input');inputs[0].value='012345';inputs[1].checked=true;form.events.submit({preventDefault(){}});assert.equal(inputs[0].value,'');response(s.calls.at(-1),{header_name:'X-CSRF',token_value:'fresh'});await flush();return form;}
test('rider clears entered PIN immediately, confirms cash, prevents overlapping mutations and refreshes workload',async()=>{const s=rider();await initialize(s);const form=await submit(s);assert.equal(s.calls[2].path,'/shop/api/v1/delivery/orders/ord_one/complete');assert.deepEqual(JSON.parse(s.calls[2].options.body),{pin:'012345',cash_received:true});assert.equal(s.calls[2].options.headers['X-CSRF'],'fresh');form.events.submit({preventDefault(){}});assert.equal(s.calls.length,3);response(s.calls[2],null);await flush();response(s.calls[3],{items:[]});await flush();assert.equal(s.ids['delivery-count'].textContent,'Assigned orders: 0');assert.equal(s.ids['delivery-list'].children[0].textContent,'No active deliveries.');});
test('ambiguous completion blocks further saves until refresh; wrong PIN allows a fresh entry',async()=>{const s=rider();await initialize(s);const form=await submit(s);s.calls[2].reject(new TypeError('Connection lost'));await flush();assert.equal(form.querySelectorAll('button')[0].disabled,true);form.events.submit({preventDefault(){}});assert.equal(s.calls.length,3);s.ids['delivery-refresh'].events.click();response(s.calls[3],{items:[order]});await flush();const retry=await submit(s);response(s.calls[5],null,422);await flush();assert.equal(retry.querySelectorAll('button')[0].disabled,false);assert.match(s.ids['delivery-message'].textContent,/Incorrect PIN/);});
test('rider departure clears private content and rejects late lists; restored pages reload',async()=>{const s=rider();s.events.pagehide();response(s.calls[0],{items:[order]});await flush();assert.equal(s.ids['delivery-list'].children.length,0);s.events.pageshow({persisted:true});assert.equal(s.events.reloaded,true);});
function cash(){const ids=Object.fromEntries(['cash-filters','cash-list','cash-error','cash-totals','cash-page','cash-prev','cash-next','cash-refresh'].map(id=>[id,element()])),calls=[],confirmations=[];vm.runInNewContext(fs.readFileSync('public/assets/js/admin-cash.js','utf8'),{document:{getElementById:id=>ids[id],createElement:element},window:{SabjiwalahAdmin:{api:(path,options)=>new Promise((resolve,reject)=>calls.push({path,options,resolve,reject})),confirm:async options=>{confirmations.push(options);return true;}}},FormData:class{*[Symbol.iterator](){yield ['status','pending'];}},URLSearchParams,Intl,Date,Math,encodeURIComponent});return {ids,calls,confirmations};}
const ledger={items:[{uid:'ord_one',order_number:'<img sample>',rider_name:'<img rider>',cash_amount:'120.00',collected_at:'2026-10-10T07:00:00Z',reconciled_at:null}],totals:{collected:'120.00',pending:'120.00',reconciled:'0.00'},pager:{page_count:1,total:1}};
test('cash screen renders safe text and confirms the server amount without sending client amounts',async()=>{const s=cash();s.calls[0].resolve({data:ledger});await flush();assert.equal(s.ids['cash-list'].children[0].children[0].textContent,'<img sample>');const button=s.ids['cash-list'].querySelectorAll('button')[0];button.events.click();await flush();assert.match(s.confirmations[0].message,/120/);assert.equal(s.calls[1].path,'/api/v1/admin/cash/ord_one/reconcile');assert.equal(JSON.stringify(s.calls[1].options.body),'{}');s.calls[1].resolve({data:null});await flush();assert.equal(s.calls.length,3);});
test('cash network failure blocks the affected handover button and retains the record until refresh',async()=>{const s=cash();s.calls[0].resolve({data:ledger});await flush();const button=s.ids['cash-list'].querySelectorAll('button')[0];button.events.click();await flush();s.calls[1].reject(new Error('Connection lost'));await flush();assert.equal(button.disabled,true);assert.match(s.ids['cash-error'].textContent,/Refresh/);assert.equal(s.ids['cash-list'].children.length,1);s.ids['cash-refresh'].events.click();assert.equal(s.calls.length,3);});
