<?= $this->extend('admin/layout') ?>
<?= $this->section('content') ?>
<section class="admin-heading"><div><p class="admin-eyebrow">DELIVERY OPERATIONS</p><h1>Dispatch</h1><p class="admin-muted">Assign ready orders and follow pickup and delivery progress.</p></div><button class="admin-button admin-button-secondary" id="dispatch-refresh" type="button">Refresh</button></section>
<p><a href="<?= esc(site_url('admin/delivery-personnel'), 'attr') ?>">Manage delivery personnel and availability</a></p>
<form id="dispatch-filters" class="admin-card products-filters"><div class="admin-field"><label for="dispatch-search">Order number</label><input id="dispatch-search" name="search" type="search" maxlength="120"></div><div class="admin-field"><label for="dispatch-status">Progress</label><select id="dispatch-status" name="status"><option value="">Ready and out for delivery</option><option value="ready_for_delivery">Ready for delivery</option><option value="out_for_delivery">Out for delivery</option></select></div><div class="admin-field"><label for="dispatch-assignment">Assignment</label><select id="dispatch-assignment" name="assignment"><option value="">All</option><option value="unassigned">Unassigned</option><option value="assigned">Assigned</option></select></div><button class="admin-button" type="submit">Apply filters</button><button class="admin-button admin-button-secondary" type="reset">Clear</button></form>
<p class="admin-caption">Updates every 8 seconds while visible. Attention flags mean 15+ minutes ready for pickup or 30+ minutes out for delivery; these are staff review thresholds.</p>
<p class="admin-caption" id="dispatch-summary" role="status">Loading dispatch…</p><div id="dispatch-error" class="admin-alert admin-alert-error" role="alert" hidden></div><div id="dispatch-list" aria-busy="true"></div>
<nav class="orders-pagination" aria-label="Dispatch pages"><button id="dispatch-prev" class="admin-button admin-button-secondary" type="button" disabled>Previous</button><span id="dispatch-page" role="status"></span><button id="dispatch-next" class="admin-button admin-button-secondary" type="button" disabled>Next</button></nav>
<dialog id="dispatch-assign" class="admin-dialog customer-details" aria-labelledby="dispatch-title"><div class="orders-detail-heading"><h2 id="dispatch-title">Assign delivery person</h2><button id="dispatch-close" class="admin-icon-button" type="button" aria-label="Close assignment">×</button></div><p id="dispatch-current" class="admin-muted"></p><p class="admin-caption">Only active, available personnel with no current orders can receive an assignment. Reassignment is allowed before pickup and retains the previous assignment history.</p>
<div id="dispatch-assign-error" class="admin-alert admin-alert-error" role="alert" hidden></div><button id="dispatch-reload" class="admin-button admin-button-secondary" type="button">Reload order and candidates</button>
<form id="dispatch-candidate-filters" class="rider-availability-form"><div class="admin-field"><label for="dispatch-candidate-search">Find available personnel</label><input id="dispatch-candidate-search" type="search" maxlength="120"></div><button id="dispatch-candidate-search-button" class="admin-button admin-button-secondary" type="submit">Search</button></form><div id="dispatch-candidates"></div>
<nav class="orders-pagination" aria-label="Available personnel pages"><button id="dispatch-candidate-prev" class="admin-button admin-button-secondary" type="button" disabled>Previous</button><span id="dispatch-candidate-page" role="status"></span><button id="dispatch-candidate-next" class="admin-button admin-button-secondary" type="button" disabled>Next</button></nav>
</dialog><noscript><p class="admin-alert admin-alert-error">Enable JavaScript to use dispatch.</p></noscript><script defer src="<?= esc(app_static_url('assets/js/admin-dispatch.js'), 'attr') ?>"></script>
<?= $this->endSection() ?>
